const { withPodfile } = require('@expo/config-plugins');

// Must exactly match the `name:` field Apple's own Package.swift declares (verified via
// `swift package dump-package` against https://github.com/apple/ml-stable-diffusion) — NOT an
// arbitrary label we get to choose. cocoapods-spm resolves a `spm_dependency` by looking up this
// identifier against the checked-out package's *actual* declared name (see
// cocoapods-spm's lib/cocoapods-spm/swift/package/project_packages.rb#pkg_desc_of and
// description.rb#use_default_xcode_linking?, which both key off the real SPM package name) — a
// mismatched identifier here fails late, with a confusing "Package description of `X` does not
// exist!" error rather than a naming-mismatch error.
const PACKAGE_ID = 'stable-diffusion';
const PLUGIN_LINE = "plugin 'cocoapods-spm'";
// `:products => []` matters: with no `:products` option, `spm_pkg` defaults to auto-linking one
// product with the *same name as the package* to the app's aggregate target — Apple's package is
// named "stable-diffusion" but its product is "StableDiffusion", so that default guess is wrong
// and pod install fails validation ("Package `stable-diffusion` does not contain product
// `stable-diffusion`"). `:products => []` suppresses that auto-link; the real product is linked
// explicitly instead, via ReactNativeImageGen.podspec's `s.spm_dependency
// "stable-diffusion/StableDiffusion"`.
const SPM_PKG_LINE = `spm_pkg '${PACKAGE_ID}', :git => 'https://github.com/apple/ml-stable-diffusion.git', :branch => 'main', :products => []`;

const POST_INSTALL_MARKER = '# withStableDiffusionSpmPackage: pre-create missing resource xcfilelists';
// StableDiffusion depends on swift-transformers, which declares SPM `resources:` — but the
// `Pods-<target>` aggregate target has no CocoaPods-level resources of its own, so CocoaPods
// never creates its `-resources-<config>-input/output-files.xcfilelist` files. cocoapods-spm's
// post_integrate hook (lib/cocoapods-spm/hooks/post_integrate/21.update_copy_resources_script.rb)
// unconditionally opens those files in "r+" mode to append the SPM resource paths, which requires
// them to already exist, and crashes with Errno::ENOENT when they don't
// ("Pods-offlineai-resources-Debug-input-files.xcfilelist"). Pre-creating them as empty files
// here (in the Podfile's own `post_install`, which — per CocoaPods' hook lifecycle — runs before
// cocoapods-spm's later `post_integrate` hook) works around it.
const POST_INSTALL_PATCH = `    ${POST_INSTALL_MARKER}
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_build_configurations.each_key do |config|
        [
          aggregate_target.copy_resources_script_input_files_path(config),
          aggregate_target.copy_resources_script_output_files_path(config),
        ].each do |path|
          FileUtils.mkdir_p(File.dirname(path))
          FileUtils.touch(path) unless File.exist?(path)
        end
      end
    end
`;

/**
 * `ios/` is regenerated by `expo prebuild` (gitignored — see apps/offline-ai/.gitignore's
 * "generated native folders" section), so a manual edit to ios/Podfile doesn't survive a clean
 * prebuild. This plugin re-applies the two Podfile lines the `cocoapods-spm` CocoaPods plugin
 * needs every time the Podfile is generated, so `pod install` can resolve
 * ReactNativeImageGen.podspec's `s.spm_dependency "stable-diffusion/StableDiffusion"` — Apple's
 * ml-stable-diffusion pipeline is SPM-only and has no published podspec, so plain CocoaPods can't
 * resolve it as a normal `pod` dependency. See packages/react-native-image-gen/README.md.
 *
 * Requires the `cocoapods-spm` gem to be installed where `pod install` runs (see
 * apps/offline-ai/Gemfile) — this plugin only edits the Podfile text, it doesn't install gems.
 */
function withStableDiffusionSpmPackage(config) {
  return withPodfile(config, (config) => {
    let contents = config.modResults.contents;

    if (!contents.includes(PLUGIN_LINE)) {
      contents = `${PLUGIN_LINE}\n${contents}`;
    }
    if (!contents.includes(SPM_PKG_LINE)) {
      contents = contents.replace(PLUGIN_LINE, `${PLUGIN_LINE}\n\n${SPM_PKG_LINE}`);
    }

    // Must land inside the *existing* `post_install do |installer|` block (added by Expo's own
    // template, for react_native_post_install) — CocoaPods' Podfile DSL keeps only the last
    // `post_install` block if there are two, so adding a second one would silently drop React
    // Native's required post-install step instead of running alongside it.
    if (!contents.includes(POST_INSTALL_MARKER)) {
      const target = 'post_install do |installer|';
      if (!contents.includes(target)) {
        throw new Error(
          "withStableDiffusionSpmPackage: couldn't find 'post_install do |installer|' in the generated Podfile to patch — Expo's template may have changed."
        );
      }
      contents = contents.replace(target, `${target}\n${POST_INSTALL_PATCH}`);
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withStableDiffusionSpmPackage;
